baseURL = "https://eortizromero.github.io/quickstart"
languageCode = "es-mx"
title = "Desarrollador Python Blog"

theme = "hugo-theme-chunky-poster"
publishDir = "docs"

[params]
    author = "Edgardo Ortiz"
    description = "Blog para desarrolladores Python"
